export type RiskTolerance = "conservative" | "balanced" | "aggressive";

export type Opportunity = {
  id: string;
  title: string;
  sector: string;
  type: string;
  country: string;
  city: string;
  askingPrice: number;
  requiredInvestment: number;
  currency: string;
  description: string;
  revenue?: number;
  ebitda?: number;
  assetsIncluded: string;
  employees?: number;
  size: string;
  seller: string;
  url: string;
  publicationDate: string;
  retrievedDate: string;
  contact: string;
  dataCompleteness: number;
  sourceReliability: number;
  warnings: string[];
  scores: {
    expectedReturn: number;
    downsideResilience: number;
    marketAttractiveness: number;
    askingPrice: number;
    cashFlowQuality: number;
    strategicFit: number;
    dataReliability: number;
    liquidity: number;
    riskPenalty: number;
  };
  recommendation: string;
  thesis: string;
  principalRisks: string[];
  valuationRange: [number, number];
  baseReturn: number;
  downsideReturn: number;
  paybackYears: number;
  riskLevel: "Low" | "Medium" | "High";
};

export type InvestorProfile = {
  fullName: string;
  email: string;
  capital: number;
  minInvestment: number;
  maxInvestment: number;
  country: string;
  locations: string;
  industries: string[];
  excludedIndustries: string;
  role: "Active" | "Passive";
  structure: string;
  riskTolerance: RiskTolerance;
  minimumReturn: number;
  maxPayback: number;
  horizon: string;
  financing: boolean;
  equityContribution: number;
  currency: string;
  liquidity: string;
  esg: string;
  experience: string;
  notes: string;
  legalConfirmation: boolean;
};
